/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdministrationRouteImport } from './routes/administration'
import { Route as AdmissionRouteImport } from './routes/admission'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as EventsRouteImport } from './routes/events'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as PortalRoleRouteImport } from './routes/portal.$role'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationRoute = AdministrationRouteImport.update({
  id: '/administration',
  path: '/administration',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionRoute = AdmissionRouteImport.update({
  id: '/admission',
  path: '/admission',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoleRoute = PortalRoleRouteImport.update({
  id: '/portal/$role',
  path: '/portal/$role',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/administration': typeof AdministrationRoute
  '/admission': typeof AdmissionRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/programs': typeof ProgramsRoute
  '/portal/$role': typeof PortalRoleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/administration': typeof AdministrationRoute
  '/admission': typeof AdmissionRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/programs': typeof ProgramsRoute
  '/portal/$role': typeof PortalRoleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/administration': typeof AdministrationRoute
  '/admission': typeof AdmissionRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/programs': typeof ProgramsRoute
  '/portal/$role': typeof PortalRoleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/administration'
    | '/admission'
    | '/contact'
    | '/donate'
    | '/events'
    | '/gallery'
    | '/programs'
    | '/portal/$role'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/administration'
    | '/admission'
    | '/contact'
    | '/donate'
    | '/events'
    | '/gallery'
    | '/programs'
    | '/portal/$role'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/administration'
    | '/admission'
    | '/contact'
    | '/donate'
    | '/events'
    | '/gallery'
    | '/programs'
    | '/portal/$role'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdministrationRoute: typeof AdministrationRoute
  AdmissionRoute: typeof AdmissionRoute
  ContactRoute: typeof ContactRoute
  DonateRoute: typeof DonateRoute
  EventsRoute: typeof EventsRoute
  GalleryRoute: typeof GalleryRoute
  ProgramsRoute: typeof ProgramsRoute
  PortalRoleRoute: typeof PortalRoleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration': {
      id: '/administration'
      path: '/administration'
      fullPath: '/administration'
      preLoaderRoute: typeof AdministrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admission': {
      id: '/admission'
      path: '/admission'
      fullPath: '/admission'
      preLoaderRoute: typeof AdmissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/$role': {
      id: '/portal/$role'
      path: '/portal/$role'
      fullPath: '/portal/$role'
      preLoaderRoute: typeof PortalRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdministrationRoute: AdministrationRoute,
  AdmissionRoute: AdmissionRoute,
  ContactRoute: ContactRoute,
  DonateRoute: DonateRoute,
  EventsRoute: EventsRoute,
  GalleryRoute: GalleryRoute,
  ProgramsRoute: ProgramsRoute,
  PortalRoleRoute: PortalRoleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
